### ISSUE TITLE
소중한 Github 스토리지를 보호해주세요

### ISSUE THREAD

**Issue by SuchangKo** [chester777/My-Ideal#1]
소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요소중한 Github 스토리지를 보호해주세요

**Comment by chester777** [comment]
소중한 첫 이슈 감사합니다.

다만 해당 레포지토리는 특별한 이유가 있지 않는 한 이슈트래킹을 하지 않습니다.

아쉽지만 여기서 본 이슈는 마감하겠습니다 ㅠㅠ
